version: '3.7'
services:
  keycloak:
    container_name: keycloak
    hostname: keycloak
    image: quay.io/keycloak/keycloak:10.0.1
    ports:
      - 8000:8080
    environment:
      - KEYCLOAK_USER=servicestarter
      - KEYCLOAK_PASSWORD=servicestarter
    volumes:
      - ./keycloak:/opt/jboss/keycloak/imports
    command:
      - "-b 0.0.0.0 -Dkeycloak.import=/opt/jboss/keycloak/imports/realm-export.json"
      - "-Dkeycloak.profile.feature.upload_scripts=enabled"
    networks:
      - calculatornetwork

