version: '3.7'
services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=calculator
      - POSTGRES_USER=calculator
      - POSTGRES_PASSWORD=postgres
    networks:
      - calculatornetwork